services:
  - type: web
    name: mern-graphql-backend
    env: node
    rootDir: server
    buildCommand: npm install && npm run build:client
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        sync: false  # Lo configurar√°s manualmente
      - key: PORT
        value: 10000